# Enable Bluetooth subsystem
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
# Change this string to force your iPhone to overwrite its cache
CONFIG_BT_DEVICE_NAME="GreenCaddie Pro"

# Force high-throughput connection parameter intervals
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=12
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=24
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

# Expand the maximum allowed concurrent L2CAP and ATT transmit packet allocations
CONFIG_BT_L2CAP_TX_BUF_COUNT=10
CONFIG_BT_BUF_ACL_TX_COUNT=10

# Increase Event RX buffer count to satisfy the compiler build assertions
CONFIG_BT_BUF_EVT_RX_COUNT=11

# Increase the overall Network Buffer pool count to support continuous high-rate notifications
CONFIG_BT_CONN_TX_MAX=10

# Enable I2C and Sensor Framework APIs
CONFIG_I2C=y
CONFIG_SENSOR=y

# Enable DPS310 Sensor Driver
CONFIG_DPS310=y

# Allow sprintf/snprintk to convert floats into printable strings
CONFIG_CBPRINTF_FP_SUPPORT=y
